### ISSUE TITLE
Security data exposed

### ISSUE THREAD

**Issue by elizabethsn7** [specula-eu/specula-app#1]
AWS Access Key is Exposed

Please follow the instructions below and take steps to prevent any new credentials from being publicly exposed.

• DELETE THE IAM USER
Rotating the exposed key is not sufficient to protect your account. In order to protect your account, you must delete the User associated with the exposed key. Navigate to your IAM Users list in the AWS Management Console, here: https://console.aws.amazon.com/iam/home#users. Please select the IAM user identified above, then click on the “Delete user” button in red. On the confirmation page, select “Yes, delete”.

• CHECK FOR UNAUTHORIZED USAGE
We strongly encourage you to immediately review your AWS account for any unauthorized AWS usage, suspect running instances, or inappropriate IAM users and policies. To check the usage, please log into your AWS Management Console and go to each service page to see what resources are being used. Please pay special attention to the running EC2 instances and IAM users, roles, and groups. You can also check for any unexpected usage on the "Bills" page in the Billing console. https://console.aws.amazon.com/billing/home#/bill

Please keep in mind that unauthorized usage can occur in any region and that in your console you only see one region at a time. To switch between regions, you can use the dropdown in the top-right corner of the console screen.

**Comment by cgobbet** [comment]
Users changed. Compromised user deleted. New credentials updated to Serverless/AWS. Live site apparently running ok.
